# Generated by Django 5.0.4 on 2024-05-16 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='hobbies',
        ),
    ]
